services:

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    entrypoint: /app/docker-entrypoint.sh
    command: sh -c "npm install && npm run dev"
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_BACKEND_URL: http://localhost:1337

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/scripts:/opt/app/scripts
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
      - 5173:5173
    depends_on:
      - db
    environment:
      APP_KEYS: "mAzXoQi1qI3PzEhF1MNWPA==,dEkYXLPUuSlC26STB0ZyKA=="
      API_TOKEN_SALT: Lniabeo/mh7ynqF/GTfpOw==
      ADMIN_JWT_SECRET: Hr+r0OSOTgUzfce6q9/AvA==
      TRANSFER_TOKEN_SALT: 95PYtBD/vlf9x0fB76N/sw==
      JWT_SECRET: T+8DOhQmklZ+TH7ihClOKg==
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: science_of_africa
      DATABASE_USERNAME: akvo
      DATABASE_PASSWORD: password
      DATABASE_SSL: false
      EMAIL_CONFIRMATION_URL: http://localhost:3000/verify-email
      PASSWORD_RESET_URL: http://localhost:3000/reset-password
      PLUGIN_PROVIDERS: ${PLUGIN_PROVIDERS:-local}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      GCS_SERVICE_ACCOUNT: ${GCS_SERVICE_ACCOUNT:-{}}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME:-}
      GCS_BASE_PATH: ${GCS_BASE_PATH:-}
      GCS_BASE_URL: ${GCS_BASE_URL:-}
      GCS_PUBLIC_FILES: ${GCS_PUBLIC_FILES:-}
      GCS_UNIFORM: ${GCS_UNIFORM:-}

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password

  mailpit:
    image: axllent/mailpit:v1.21
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pg-data:
  pgadmin-data:
